Also staged changes in VS Code, maybe this will work?
KatieMurphy98/Year-4-Project pull request #21
Opened 2020-11-13 13:09 UTC by KatieMurphy98

2020-11-23 11:05 UTC, drvinceknight requested changes
Some minor stylistic tweeks, and let us add a stylcheck to the CI. Once those are done I'll look through the code.

2020-11-23 11:05 UTC, drvinceknight commented on Data/AKC Dog Breeds/main.csv
> +Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
Let's remove the data files from version control but include information about how to get them in the respective READMEs.

2020-11-23 11:05 UTC, drvinceknight commented on src/R/main.R
> +NinjaWarrior <- read.csv("C:/Users/Katie/OneDrive/Uni_Work_Year4/Project/Data/American Ninja Warrior Obstacle History.csv")
Use a relative path.

2020-11-23 11:05 UTC, drvinceknight commented on src/R/main.R
> +obstacles <- function(ObstacleNumbers){
Let's document these functions. See https://style.tidyverse.org/documentation.html

2020-11-23 11:05 UTC, drvinceknight commented on src/py/main.py
> +Dogs = pd.read_csv('C://Users//Katie//OneDrive//Uni_Work_Year4//Project//Data//AKC Breed Info.csv')
Relative path.

2020-11-23 11:05 UTC, drvinceknight commented on src/py/main.py
> +
Not here.

2020-11-23 11:05 UTC, drvinceknight commented on src/R/main.R
> +library(viridis) #colourmaps
```suggestion
library(ggplot2)
library(dplyr)
library(DAAG)
library(viridis)
```

2020-11-23 11:05 UTC, drvinceknight commented on src/R/main.R
> +theme_classic()
Let's save this plots to a directory.

2020-11-23 11:05 UTC, drvinceknight commented on src/R/main.R
> +theme_classic()
(It's often sensible not to include pdfs in version control but we will here.)

2020-11-23 11:06 UTC, drvinceknight commented on src/R/main.R
> +library(viridis) #colourmaps
Don't use comments unless you need to: document instead. (We can discuss what that means.)

2021-01-01 17:28 UTC, KatieMurphy98 reviewed
NOTE: Found a sales dataset in R library 'datasets' package to take values from

2021-05-12 16:20 UTC, merged